### PR TITLE
Multi node NSM GoGTP case

### PR DESCRIPTION
**Pull request by nicoekkart**
Implemented a first version of GoGTP with NSM.

**Todo:** 

- Add a readme
- Code to find IP's and interface names is hacky. I didn't find a better way to do this.

### CODE REVIEW

**Comment by taylor** [comment]
@nicoekkart I'm good with the code as a first version. Finding the IPs and interfaces can be updated later.  Would you provide a README and mark the PR ready for review?  Then we can merge.

**Comment by taylor** [comment]
@electrocucaracha  this could be a reference for your nsm example.  might be useful to keep a second one also.  please review

**Comment by taylor** [comment]
ref https://github.com/cncf/cnf-testbed/pull/342

**Comment by nicoekkart** [comment]
I'll try to fix it this weekend.

**Comment by electrocucaracha** [comment]
@nicoekkart , I'm not sure that using the GoGTP images as they are is the right approach for this, I'll explore the possibility to separate Control plane from User plane on this. I'll share my results later.

**Comment by taylor** [comment]
@nicoekkart closing this out. If you have time in the future please open a PR again with the remaining items.

**Pull request closed without merging**
